/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _codehandlerslota_h_
#define _codehandlerslota_h_
//---------------------------------------------------------------------------------
extern const unsigned char codehandlerslota[];
extern const int codehandlerslota_size;
//---------------------------------------------------------------------------------
#endif //_codehandlerslota_h_
//---------------------------------------------------------------------------------
