#include <gctypes.h>
#include "disc.h"

#ifndef _LANGUAGE_H_
#define _LANGUAGE_H_

#ifdef __cplusplus
extern "C"
{
#endif

struct LANGUAGE
{

	char t3Covers[50];
	char addToFavorite[50];
	char all[30];
	char AppLanguage[50];
	char available[20];
	char Areyousure[50];
	char AutoPatch[30];
	char Back[20];
	char Backgroundmusic[80];
	char Backgroundmusicpath[100];
	char BacktoHBCorWiiMenu[50];
	char BacktoLoader[50];
	char BacktoWiiMenu[50];
	char BootStandard[50];
	char Both[35];
	char Cantcreatedirectory[50];
	char Cancel[20];
	char Cantbeformated[50];
	char Cantdelete[50];
	char CheckingforUpdates[40];
	char ClicktoDownloadCovers[50];
	char Clock[20];
	char Close[20];
	char Continueinstallgame[50];
	char ConsoleDefault[50];
	char Consoleshouldbeunlockedtomodifyit[100];
	char ConsoleLocked[50];
	char CorrectPassword[50];
	char Couldnotinitializenetwork[50];
	char CouldnotopenDisc[50];
	char CouldnotinitializeDIPmodule[60];
	char CoverDownload[50];
	char CoverPath[50];
	char CoverpathChanged[50];
	char Coverpathchange[50];
	char count[20];
	char Credits[30];
	char DiscImages[50];
	char DiscimagePath[50];
	char DiscpathChanged[50];
	char Discpathchange[50];
	char DiscDefault[50];
	char Display[30];
	char Doyouwanttoformat[50];
	char Doyoureallywanttodelete[50];
	char Doyouwanttoretryfor30secs[80];
	char Doyouwanttoupdate[50];
	char Downloadingfile[50];
	char DownloadBoxartimage[50];
	char Downloadfinished[50];
	char Defaultgamesettings[50];
	char Defaultsettings[40];
	char Error[30];
	char BOOTERROR[50];
	char ErrorreadingDisc[50];
	char ExitUSBISOLoader[50];
	char InitializingNetwork[50];
	char InsertDisk[50];
	char InsertaWiiDisc[50];
	char InsertaSDCardtodownloadimages[80];
	char InsertaSDCardtosave[60];
	char InsertaSDCardtousethatoption[100];
	char InstallRenameandDeleteareunlocked[100];
	char Installerror[50];
	char Installagame[50];
	char Installinggame[50];
	char Failedtoboot[50];
	char FailedtomountfrontSDcard[80];
	char FailedtosetUSB[50];
	char Failedformating[50];
	char fave[15];
	char Filenotfound[50];
	char filesnotfoundontheserver[80];
	char filesleft[50];
	char FlipX[50];
	char Force[50];
	char Youneedtoformatapartition[80];
	char Format[50];
	char Formattingpleasewait[70];
	char formated[30];
	char free[30];
	char FreeSpace[50];
	char FullShutdown[50];
	char GameID[30];
	char Games[50];
	char Gameisalreadyinstalled[90];
	char GameRegion[50];
	char GameSize[50];
	char GoBack[50];
	char GotoPage[50];///////
	char HowtoShutdown[50];
	char Homemenu[30];
	char hour[30];
	char keyboard[50];
	char Language[50];
	char Langchange[50];
	char Left[50];
	char LikeSysMenu[50];
	char ListSort[30];
	char LoadingincIOS[50];
	char Loadingstandardlanguage[80];
	char Loadingstandardmusic[80];
	char Lock[30];
	char LockConsole[50];
	char MP3Menu[40];
	char Missingfiles[50];
	char Networkiniterror[50];
	char Neither[40];
	char Next[40];
	char No[40];
	char Nofilemissing[50];
	char NoHDDfound[40];
	char NoSDcardinserted[50];
	char Nopartitionsfound[50];
	char NoUSBDevice[40];
	char NoWBFSpartitionfound[50];
	char Nonewupdates[40];
	char NormalCovers[40];
	char Normal[30];
	char NotaWiiDisc[40];
	char NoUSBDevicefound[50];
	char Notenoughfreespace[50];
	char Notasupportedformat[100];
	char notset[40];
	char of[30];
	char OFF[30];
	char OfficialSite[50];
	char ok[30];
	char ON[30];
	char OnlyInstall[50];
	char Parentalcontrol[50];
	char Partition[50];
	char Password[50];
	char PasswordChanged[50];
	char Passwordhasbeenchanged[80];
	char Passwordchange[50];
	char PowerofftheWii[50];
	char Plays[20];
	char Prev[50];
	char PromptsButtons[50];
	char ReloadSD[50];
	char RenameGameonWBFS[50];
	char Restart[30];
	char Restarting[20];
	char Return[30];
	char ReturntoWiiMenu[50];
	char Right[30];
	char Rumble[30];
	char QuickBoot[50];
	char Save[30];
	char SaveFailed[50];
	char Specialthanksto[50];
	char For[20];
	char theUSBLoaderandreleasingthesourcecode[100];
	char secondsleft[50];
	char SelectthePartition[50];
	char youwanttoformat[50];
	char settings[50];
	char Setasbackgroundmusic[90];
	char Standard[30];
	char ShutdowntoIdle[50];
	char ShutdownSystem[50];
	char Success[30];
	char Successfullyinstalled[80];
	char Successfullyupdated[70];
	char Successfullydeleted[60];
	char SuccessfullySaved[50];
	char SystemDefault[50];
	char ThemePath[50];
	char ThemepathChanged[50];
	char Themepathchange[80];
	char Titlestxtpath[80];
	char Titlestxtpathchange[80];
	char TitlestxtpathChanged[80];
	char Try[30];
	char Tooltips[50];
	char Timeleft[50];
	char Unlock[50];
	char Unicodefix[50];
	char Uninstall[50];
	char USBLoaderisprotected[80];
	char USBDevicenotfound[80];
	char updating[25];
	char Updatepath[50];
	char Updatepathchanged[50];
	char Updatefailed[40];
	char VideoMode[50];
	char VIDTVPatch[50];
	char Volume[50];
	char Waiting[50];
	char WaitingforUSBDevice[80];
	char WidescreenFix[50];
	char WiiMenu[50];
	char Wiilight[20];
	char WrongPassword[50];
	char Yes[20];
	char YoudonthavecIOS[70];
	char Japanese[30];
	char German[30];
	char English[30];
	char French[30];
	char Spanish[30];
	char Italian[30];
	char Dutch[30];
	char SChinese[30];
	char TChinese[30];
	char Korean[30];
};

extern struct LANGUAGE LANGUAGE;

char* strcopy(char *dest, char *src, int size);
bool checkfile(char * path);
void lang_default();
void language_set(char *name, char *val);

#ifdef __cplusplus
}
#endif

#endif
